language: node_js
node_js: 10
dist: trusty

before_install:
  - npm install -g yarn

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: build
    target_branch: gh-pages
    on:
      branch: master